export TERM="xterm-256color"

# ZSH/Oh-my-zsh stuff
export ZSH=~/.oh-my-zsh
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()         # (status battery time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)

# Set Vim runtime path (this could vary based on system)
export VIMRUNTIME=/usr/local/share/vim/vim81

# Export lang vars
export LC_ALL="en_GB.utf8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_GB.UTF-8"

# SSH keys fix for Mac OS
ssh-add -K &> /dev/null

# Set editor variable
export EDITOR='vim'

# Set Go required env vars
export GOPATH=$HOME/subito-envs
export GOBIN=$GOPATH/bin

# Source aliases
source ~/.bash_aliases

# Set PATH var
export PATH="$PATH:$GOBIN:/usr/local/opt/go/libexec/bin:$HOME/.cargo/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Source custom settings, if any
if [ -f ~/.zsh_custom ]; then
    source ~/.zsh_custom
fi
