export TERM="xterm-256color"

# ZSH/Oh-my-zsh stuff
export ZSH=~/.oh-my-zsh
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting npm)
source $ZSH/oh-my-zsh.sh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)         # (status battery time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)

# Export lang vars
export LC_ALL="en_GB.utf8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_GB.UTF-8"

# SSH keys fix for Mac OS
ssh-add -K &> /dev/null

# Set editor variable
export EDITOR='vim'

# Set Go required env vars
export GOPATH=$HOME/workspace
export GOBIN=$GOPATH/bin

# Source aliases
source ~/.bash_aliases

# Set PATH var
export PATH="$PATH:$GOBIN:/usr/local/opt/go/libexec/bin:$HOME/.cargo/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:$HOME/.local/bin"

# Source custom settings, if any
if [ -f ~/.zsh_custom ]; then
    source ~/.zsh_custom
fi

# MacOS-specific adjustments
if [ "$(uname)" "==" "Darwin" ]; then
    # Vim runtime
    export VIMRUNTIME=/usr/local/share/vim/vim82

    # Autojump
    [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
fi
